brands = [
    "Alexander, Mercado and West",
    "Bailey-Johnston",
    "Barnett Group",
    "Barton, Murray and Huber",
    "Brown-Vega",
    "Bryant, Novak and Burns",
    "Carlson Group",
    "Coleman Inc",
    "Cummings, Silva and Galloway",
    "Decker, Carter and Dunn",
    "Duncan and Sons",
    "Duran-Thompson",
    "Evans-Bell",
    "Farley and Sons",
    "Farmer, Pace and Saunders",
    "Fitzgerald, Delgado and Williams",
    "Fox Group",
    "Garner-Martinez",
    "Green PLC",
    "Hall, Price and Mccarthy",
    "Hammond Inc",
    "Hayes-Ali",
    "Ho-Hall",
    "Holden and Sons",
    "Jimenez, Baker and Davenport",
    "Jones, Anderson and Mcintyre",
    "Long, Jones and Carter",
    "Mitchell-Smith",
    "Moore, Peters and Freeman",
    "Moore-Wagner",
    "Parker-Fischer",
    "Peters-Hanna",
    "Peters-Mclaughlin",
    "Roberts, Sparks and Rose",
    "Salinas-Glenn",
    "Sharp Ltd",
    "Simmons, Diaz and Alexander",
    "Small-Anthony",
    "Smith LLC",
    "Smith, Jackson and George",
    "Smith-Hunter",
    "Taylor PLC",
    "Thomas-Thompson",
    "Velasquez, Nicholson and Burton",
    "Vincent, Collins and Arnold",
    "Walton-Stewart",
    "Ward-Olsen",
    "Watts, Fisher and Shah",
    "West PLC",
    "Yoder-Bradley",
]
